### ISSUE TITLE
confusing behavior with nested wait.for calls

### ISSUE THREAD

**Issue by yelworc** [luciotato/waitfor#22]
Nested calls of `wait.for` currently cause an error ("Callback for function ... called twice") and confusing behavior. Example ([gist](https://gist.github.com/yelworc/da3a563ea73e54eb6b2c#file-nested-waitfor-js)):

``` javascript
function g(callback) {
    setImmediate(function () {
        callback(null, 'G');
    });
}

function f(callback) {
    var res_g = wait.for(g);
    setImmediate(function () {
        callback(null, 'F' + res_g);
    });
}

wait.launchFiber(function () {
    var res_f = wait.for(f);
    console.log('alleged result of f(): ' + res_f);
});
```

Output:

```
$ node --harmony nested-waitfor.js
alleged result of f(): G

node_modules/wait.for/waitfor.js:28
                                 throw new Error("Callback for function "+fnNa
                                       ^
Error: Callback for function f called twice. Wait.for already resumed the execution.
    at resumeCallback (node_modules/wait.for/waitfor.js:28:40)
    at Object._onImmediate (nested-waitfor.js:14:3)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

The result of the inner function `g` is returned to the caller of the outer function `f`, _before_ the error is thrown. In real-life use, this makes debugging quite a bit more difficult.

I'm not sure if this is considered a bug or incorrect usage. Looking at the code (and [this related issue](https://github.com/luciotato/waitfor/issues/9)), the behavior seems to be by design: all the properties like `callbackAlreadyCalled` are attached to the fiber, so can't really support nested invocations.

If it is by design, this should be mentioned in the docs IMHO, and perhaps the error behavior can be improved.

**Comment by darrudi** [comment]
+1
