### ISSUE TITLE
problem installing wait.for with npm

### ISSUE THREAD

**Issue by theRemix** [luciotato/waitfor#39]
i'm getting this error with node 5.0.0 npm 3.3.6

`npm install wait.for`

```
...
SOLINK_MODULE(target) Release/fibers.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/fibers.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/me/myapp/node_modules/wait.for/node_modules/fibers
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
 CXX(target) Release/obj.target/fibers/src/fibers.o
./Release/.deps/Release/obj.target/fibers/src/fibers.o.d.raw { dev: 16777220,
 mode: 33188,
 nlink: 1,
 uid: 501,
 gid: 20,
 rdev: 0,
 blksize: 4096,
 ino: 41052426,
 size: 427,
 blocks: 8,
 atime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST),
 mtime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST),
 ctime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST),
 birthtime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST) }
 CXX(target) Release/obj.target/fibers/src/coroutine.o
./Release/.deps/Release/obj.target/fibers/src/coroutine.o.d.raw { dev: 16777220,
 mode: 33188,
 nlink: 1,
 uid: 501,
 gid: 20,
 rdev: 0,
 blksize: 4096,
 ino: 41052429,
 size: 433,
 blocks: 8,
 atime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST),
 mtime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST),
 ctime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST),
 birthtime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST) }
 CC(target) Release/obj.target/fibers/src/libcoro/coro.o
./Release/.deps/Release/obj.target/fibers/src/libcoro/coro.o.d.raw { dev: 16777220,
 mode: 33188,
 nlink: 1,
 uid: 501,
 gid: 20,
 rdev: 0,
 blksize: 4096,
 ino: 41052434,
 size: 94,
 blocks: 8,
 atime: Mon Nov 16 2015 13:33:28 GMT-1000 (HST),
 mtime: Mon Nov 16 2015 13:33:28 GMT-1000 (HST),
 ctime: Mon Nov 16 2015 13:33:28 GMT-1000 (HST),
 birthtime: Mon Nov 16 2015 13:33:27 GMT-1000 (HST) }
 SOLINK_MODULE(target) Release/fibers.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`gcc -v`
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

any ideas?

**Comment by luciotato** [comment]
Yes, wait.for uses Fibers, https://github.com/laverdet/node-fibers, and
"Fibers" compiles on install

Option 1) You need to solve the problem on installing fibers on
darwin, see: https://github.com/laverdet/node-fibers/issues/182

Option 2) try https://github.com/luciotato/waitfor-ES6




Cordiales Saludos,
Lucio M. Tato
Socio Gerente
www.tecnogob.com

**Comment by theRemix** [comment]
switching to `wait.for-es6` did the trick, thank you @luciotato
